---
# tasks file for ntp

- name: Install NTP package.
  apt:
    name: ntp
    state: present
    update_cache: yes

- name: Add Iptables rules
  include: iptables.yml
  when: iptables_enabled

- name: Start the ntp service
  systemd:
    name: ntp
    state: started
    enabled: true