---
# tasks file for gitlab

- name: (GITLAB-CE) Install prerequisites
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
    - openssl
    - tzdata

- name: (GITLAB-CE) Check if GitLab-CE is already installed
  stat:
    path: /etc/gitlab
  register: gitlab

- name: (GITLAB-CE) Download GitLab-CE Deb script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/gitlab-ce.deb.sh
  when: not gitlab.stat.exists

- name: (GITLAB-CE) Execute GitLab-CE Deb script
  command: /bin/bash /tmp/gitlab-ce.deb.sh
  when: not gitlab.stat.exists

- name: (GITLAB-CE) Install GitLab Community Edition
  package:
    name: gitlab-ce
    state: latest
  register: gitlab_update

- name: (GITLAB-CE) Configure GitLab Community Edition
  command: gitlab-ctl reconfigure
  when: gitlab_update|changed


- name: Create GitLab SSL configuration folder.
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: gitlab_create_self_signed_cert

- name: Create self-signed certificate.
  command: >
    openssl req -new 
      -nodes
      -x509
      -subj "{{ gitlab_self_signed_cert_subj }}"
      -days 3650
      -keyout {{ gitlab_ssl_certificate_key }}
      -out {{ gitlab_ssl_certificate }}
      -extensions v3_ca
  when: gitlab_create_self_signed_cert

- name: Copy GitLab configuration file.
  template:
    src: "{{ gitlab_config_template }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab