---
# tasks file for apache

- name: Stop Apache server script and disable it.
  service:
    name: apache
    state: stopped
    enabled: no
  ignore_errors: true

- name: Change the right of Apache directory
  file:
    path: "{{ apache_home }}"
    owner: "{{ apache_root_user }}"
    group: "{{ apache_root_group }}"
    recurse: yes

- name: Create Group Apache
  group:
    name: "{{ apache_user_group }}"
    state: present

- name: Create User Apache without home and no Shell
  user:
    name: "{{ apache_user }}"
    createhome: no
    group: "{{ apache_user_group }}"
    shell: /bin/false
    comment: "Web Server"
    state: present

- name: Deploy configuration file for Apache
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ apache_root_user }}"
    group: "{{ apache_root_group }}"
  with_items: "{{ apache_files }}"

- name: Create Apache log directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ apache_root_user }}"
    group: "{{ apache_root_group }}"
    recurse: yes
  with_items:
    - "{{ apache_logs_dir }}"
    - "{{ apache_vhosts_dir }}"

- name: Copy Apache control script
  template:
    src: apache.sh.j2
    dest: "{{ apache_init_script }}"
    mode: 0755

- name: Enable Apache init script
  service:
    name: apache
    enabled: yes

- name: Restart Apache
  command: echo "Restart Apache"
  notify:
    - Restart Apache