---
# tasks file for apache_mod_jk
- name: Download and decompress Mod_JK library
  unarchive:
    src: "{{ mod_jk_url }}"
    dest: "{{ apache_modules_dir }}/"
    remote_src: True

- name: Set owner and group for Mod JK library
  file:
    path: "{{ apache_modules_dir }}/mod_jk.so"
    owner: "{{ apache_root_user }}"
    group: "{{ apache_root_group }}"

- name: Add Mod JK to the list of Apache's modules
  lineinfile:
    dest: "{{ apache_modules_file }}"
    insertafter: EOF
    line: 'LoadModule jk_module {{ apache_modules_dir }}/mod_jk.so'

- name: Restart Apache
  command: echo "Restart Apache"
  notify:
    - Restart Apache