---
# tasks file for openjdk8

- name: Install open JDK 8
  apt:
    name: openjdk-8-jdk
    state: present

- name: Define JAVA_HOME variable
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME="/usr/lib/jvm/default-java"'
    owner: root
    group: root

- name: Relaod environments variables
  shell: . /etc/environment