---

- hosts: vm-debian-2
  become: yes
  roles:
    - role: openjdk8
    - role: tomcat
      tomcat_goss_enabled: False
      tomcat_iptables_enabled: True
      tomcat_openssl_enabled: False
      tomcat_keystore_enabled: False
      tomcat_network_interface: "enp0s8"
      tags: ['tomcat']


###################
# Install apache
###################
- hosts: vm-debian-1
  become: yes
  roles:
    - role: apache_from_scratch
    - role: apache_vhosts_mod_proxy
      tags: ['apache_vhosts_mod_proxy']