---

###################
# Playbook to install role jenkins
###################
- hosts: vm-debian-1
  become: yes
  roles:
    - role: jenkins_master
      jenkins_network_interface: "enp0s8"
      jenkins_iptables_enabled: True
      tags: ['jekins']