---

###################
# Playbook to install role nexus
###################
- hosts: vm-debian-1
  become: yes
  roles:
    - role: nexus
      nexus_host: 192.168.56.2
      nexus_network_interface: "enp0s8"
      nexus_iptables_enabled: True
      nexus_reverse_proxy_enabled: True
      nexus_reverse_proxy_http_default_port: 80
      nexus_reverse_proxy_server_name: "nexus.syscom.com"
      tags: ['nexus']