---

###################
# Playbook to install role portsentry
###################
- hosts: vm-debian-1
  become: yes
  roles:
    - role: portsentry
      portsentry_goss_enabled: True
      tags: ['portsentry']