---

###################
# Playbook to install role postgres
###################
- hosts: serverDebian2
  become: yes
  roles:
    - role: postgres
      postgres_goss_enabled: True
      tags: ['postgres']