---

###################
# Playbook to install role SonarQube
###################
- hosts: vm-debian-1
  become: yes
  roles:
    - role: sonarqube
      sonarqube_postgres_database_enabled: True
      tags: ['sonarqube']