---

###################
# Playbook to install role ssh
###################
- hosts: serverDebian2
  become: yes
  roles:
    - role: ssh
      ssh_delete_obsolete_packages: True
      ssh_goss_enabled: True
      tags: ['ssh']