---

- hosts: localhost
  become: yes
  tasks:
  - name: Create user on local machine (Ansible host machine)
    local_action: user name=user_test comment="user_test" shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048 ssh_key_passphrase=
    no_log: True

  - name: Retrieve public key
    local_action: shell cat /home/user_test/.ssh/id_rsa.pub
    register: user_public_key
    no_log: True

- hosts: vm-debian-1
  become: yes
  roles:
    - role: sudo_users
      user_name: "user_test"
      user_password: "password"
      user_public_ssh_key: "{{ hostvars['localhost']['user_public_key']['stdout'] }}"