---
# tasks file for firewall
- name: Stop firewall script and disable it.
  systemd:
    name: firewall
    state: stopped
    enabled: no
  ignore_errors: true

- name: Install iptables package
  apt:
    pkg: iptables
    state: present

- name: Copy firewall files into directories
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
   - "{{ firewall_script_files }}"

- name: Reload systemd configuration
  systemd:
    daemon-reload: yes

- name: Enable firewall service
  systemd:
    name: firewall
    enabled: yes

- name: Start firewall service
  systemd:
    name: firewall
    state: started

- name: Test with goss
  include: goss.yml
  when: firewall_goss_enabled