---
# defaults file for apache_vhosts_mod_proxy

http_default_port: 80
https_default_port: 443
apache_home: /opt/apache2
apache_server_admin: admin@example.com
apache_vhosts_dir: "{{ apache_home }}/vhosts"
apache_logs_dir: "/var/log/apache2/logs"
apache_conf_dir: "{{ apache_home }}/conf"
apache_ssl_dir: "/etc/pki/apache"
apache_ssl_ca_dir: "{{ apache_ssl_dir }}/private_ca"
apache_httpd_file: "{{ apache_conf_dir }}/httpd.conf"
root_user: root
root_group: sys
apache_conf_log_level: warn
apache_vhosts_conf_dir: "{{ apache_conf_dir }}/vhosts"
apache_vhosts_mod_proxy:
  vhosts2:
    serverName: 'vhosts2.fr'
    serverAlias: 'www.vhosts2.fr'
    https_enabled: False
    ssl_subj: ""
    webapps: 'examples'
    host: 'vm-debian-2'
    port: '8080'
