vm-debian-1 ansible_host=192.168.56.2 ansible_connection=ssh ansible_become_pass=
vm-debian-2 ansible_host=192.168.57.2 ansible_connection=ssh ansible_become_pass=
st-db-villeurbanne ansible_host=st-db-villeurbanne ansible_connection=ssh ansible_become_pass=

[all]
vm-debian-1
vm-debian-2
st-db-villeurbanne

[ssh]
vm-debian-1