---
# tasks file for apache_vhosts

- name: Create virtual hosts configuration directories
  file:
    path: "{{ apache_vhosts_conf_dir }}"
    state: directory

- name: Create logs directories for virtual hosts
  file:
    path: "{{ apache_logs_dir }}/{{ item.key }}"
    state: directory
  with_dict: "{{ apache_vhosts }}"

- name: Create virtual hosts root directories
  file:
    path: "{{ apache_vhosts_dir }}/{{ item.key }}"
    state: directory
  with_dict: "{{ apache_vhosts }}"

- name: Create virtual mutex directories
  file:
    path: "{{ apache_vhosts_dir }}/{{ item.key }}/mutex"
    state: directory
  with_dict: "{{ apache_vhosts }}"

- name: Generate virtual hosts configuration files
  template:
    src: vhosts.conf.j2
    dest: "{{ apache_vhosts_conf_dir }}/{{ item.key }}_vhost.conf"
  with_dict: "{{ apache_vhosts }}"

- name: Install SSL certificates for virtual hosts
  include: ssl.yml

- name: Count generate virtual hosts
  find:
    paths: "{{ apache_vhosts_conf_dir }}"
    patterns: "*.conf"
    # use_regex: True
  register: count_generate_vhosts

- name: Add Virtual hosts file to HTTPD
  lineinfile:
    dest: "{{ apache_httpd_file }}"
    insertafter: EOF
    line: 'Include {{ apache_vhosts_conf_dir }}/*.conf'
  when: count_generate_vhosts.matched|int > 0

- name: Restart Apache
  command: echo "Restart Apache"
  notify:
    - Restart Apache
