---

- name: Insert/Update the block into the jail Configuration file for ssh
  blockinfile:
    dest: "{{ fail2ban_config_file }}"
    insertafter: EOF
    block: |
        [ssh]
        enabled = true
        port = ssh
        filter = sshd
        logpath = /var/log/auth.log
        maxretry = {{ fail2ban_sshd_maxretry }}
        bantime = {{ fail2ban_sshd_bantime }}
    state: present
    marker: '#'
    owner: root
    group: root
    mode: 0644