---
# tasks file for sudo_users


- name: Create user on servers machine
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment }}"
    shell: /bin/bash
    password: "{{ user_password }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_type: rsa
    ssh_key_passphrase: "{{ user_ssh_key_passphrase }}"
  no_log: True

- name: Add public key to users's authorized keys
  lineinfile:
    dest: "/home/{{ user_name }}/.ssh/authorized_keys"
    create: yes
    state: present
    mode: 0600
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    line: "{{ user_public_ssh_key }}"

- name: Install sudo package
  apt:
    pkg: sudo
    state: present

- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set includedir in sudoers
  lineinfile:
    path: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Create sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ user_name }}"
    create: yes
    state: present
    mode: 0440
    owner: root
    group: root
    line: "{{ user_name }} ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Remove sudoers
  file:
    path: "/etc/sudoers.d/{{ user_remove }}"
    state: absent
  when: (user_remove is defined) and (user_remove != None)